hydra:
  job:
    chdir: False
  run:
    dir: /root/workspace/out/modelnet40/hydra/
setup:
  seed: 1
  device: cuda
  sweep: False
  train: True
  wandb_dir: /root/workspace/out/modelnet40
load:
  connectivity: unitsphere
  radius: 0.1
  k: 4
  batch_size: 2 #1024-max 96-default
  force_reload: False
  load_checkpoint: False
  checkpoint_path: /root/workspace/out/modelnet40/noname.pt
train:
  epochs: 1000
  patience: 100
  lr : .001
  wd : 1e-16
model:
  name: schnet
  hidden_channels: 128 
  hidden_layers: 7
  attention: 1
  node_attr: 0
